// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCivKKBfs4S2Wsl-i3RGt1MO8L1DiYyqmQ',
    appId: '1:334588401907:web:f5fcfab304a5fa2a1bbf86',
    messagingSenderId: '334588401907',
    projectId: 'pizza-app-6de33',
    authDomain: 'pizza-app-6de33.firebaseapp.com',
    storageBucket: 'pizza-app-6de33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGYyRz8G-R3-3RJdNkwFZJUBnSfNcj0oo',
    appId: '1:334588401907:android:13857c3e325d3f201bbf86',
    messagingSenderId: '334588401907',
    projectId: 'pizza-app-6de33',
    storageBucket: 'pizza-app-6de33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApYaExt2GiygaOBHemrwZwXOfgPM2TFEo',
    appId: '1:334588401907:ios:51cd836f12be641c1bbf86',
    messagingSenderId: '334588401907',
    projectId: 'pizza-app-6de33',
    storageBucket: 'pizza-app-6de33.appspot.com',
    iosBundleId: 'co.knoxcorporation.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApYaExt2GiygaOBHemrwZwXOfgPM2TFEo',
    appId: '1:334588401907:ios:51cd836f12be641c1bbf86',
    messagingSenderId: '334588401907',
    projectId: 'pizza-app-6de33',
    storageBucket: 'pizza-app-6de33.appspot.com',
    iosBundleId: 'co.knoxcorporation.pizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCivKKBfs4S2Wsl-i3RGt1MO8L1DiYyqmQ',
    appId: '1:334588401907:web:dd622f6eb4f4a66f1bbf86',
    messagingSenderId: '334588401907',
    projectId: 'pizza-app-6de33',
    authDomain: 'pizza-app-6de33.firebaseapp.com',
    storageBucket: 'pizza-app-6de33.appspot.com',
  );
}
